abds([q1/0,q2/0,q3/0,q4/0,q5/0,q6/0,q7/0,q8/0,q9/0,q10/0]).
beginProlog.
s1.
s2.
s3.
s4.
s5.
s6.
s7.
s8.
s9.
s10.
endProlog.
r1 <- s1.
r2 <- s2.
r3 <- s3.
r4 <- s4.
r5 <- s5.
r6 <- s6.
r7 <- s7.
r8 <- s8.
r9 <- s9.
r10 <- s10.
p1 <- q1, r1.
p2 <- q2, r2.
p3 <- q3, r3.
p4 <- q4, r4.
p5 <- q5, r5.
p6 <- q6, r6.
p7 <- q7, r7.
p8 <- q8, r8.
p9 <- q9, r9.
p10 <- q10, r10.
a <- p1,p2,p3,p4,p5,p6,p7,p8,p9,p10.